# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapboxTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxTest

  target 'MapboxTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MapboxTest-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxTest-tvOS

  target 'MapboxTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
